# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Currently disabled as sample code is integrated elsewhere and functions
# calling exit cannot be removed.
warnings_are_errors: false

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
